project2/urls.py
from django.conf import settings
from django.conf.urls.static import static

"""project2 URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('sports.urls')),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

sports/urls.py
from django.urls import path
from . import views
app_name = 'sports'
urlpatterns = [path('', views.sportss, name='home'),
               path('loop/', views.loop, name='house'),
               path('login/', views.jaya, name='login-page'),
               path('logout/', views.out, name='logout-page'),
               path('register/', views.reg, name='register-page'),
               path('blog/', views.blog, name='blog-page'),
               path('team/', views.team, name='team-page'),
               path('contact/', views.contact, name='contact-page'),
               path('news/', views.news, name='news-page'),
               path('about/', views.about, name='about-page'),
               path('search/', views.search, name='searchresult-page'),
               path('readmore/',views.read,name='read-more')]

sports/models.py
from django.db import models


class sports(models.Model):
    date= models.DateField(auto_now_add=True)
    head= models.CharField(max_length=500)
    sub= models.CharField(max_length=10000)
    img= models.ImageField(upload_to= 'pics')

class match(models.Model):
    date= models.DateTimeField(max_length=500)
    team1= models.CharField(max_length=100)
    team2= models.CharField(max_length=100)
    logo1= models.ImageField(upload_to='isl')
    logo2= models.ImageField(upload_to='isl')


class readmore(models.Model):
    image = models.ImageField(upload_to='blog_pics')
    heading = models.CharField(max_length=400)
    discription = models.CharField(max_length=500)
    date = models.DateField(auto_now_add=True, blank=True, null=True)

sports/views.py
from django.shortcuts import render, redirect
from .models import sports,match,readmore
from django.contrib.auth.models import auth, User
from django.contrib import messages
from django.db.models import Q
from project2.settings import EMAIL_HOST_USER
from django.core.mail import send_mail

from django.http import HttpResponse

firstmatch = sports()
firstmatch.date = '1/12/1997'
firstmatch.head = 'it was a good match'
firstmatch.sub = 'fgfhagsa gfjhadvafgjshdfvns hhsgdfjbsvdcnggs sggdfnbdfsd nsgdf usgf hgfjfhsvjff'

secondmatch = sports()
secondmatch.date = '12 12 12'
secondmatch.head = 'amazing match'
secondmatch.sub = 'super kaliyaan mwone'
secondmatch.img = 'peace.jpg'

thirdmatch = sports()
thirdmatch.date = '10 10 10'
thirdmatch.head = 'shimmi hero aada hero'
thirdmatch.sub = 'mwone ath lockaa ing por'
thirdmatch.img = 'psyco.jpeg'

fourmatch = sports()
fourmatch.date = '12 12 1998'
fourmatch.head = 'vamban game'
fourmatch.sub = 'walare migacha onn'
fourmatch.img = 'messi.jpg'
fourmatch.img = 'ronu.jpg'
fourmatch.img = 'vijay.jpg'

lis = [firstmatch, secondmatch, thirdmatch, fourmatch]


def sportss(request):
    m=match.objects.all()
    return render(request, 'index.html', {'fm': firstmatch, 'sm': secondmatch, 'tm': thirdmatch,match:"m"})




def loop(request):
    return render(request, 'forloop.html', {'f': lis})


def jaya(request):
    if request.method == 'POST':
        a = request.POST['name']
        b = request.POST['password']
        user = auth.authenticate(username=a, password=b)
        if user is not None:
            auth.login(request, user)
            return redirect('sports:home')
        else:
            messages.error(request, "invalid username/password")

    return render(request, 'login.html')

def out(request):
    auth.logout(request)
    return redirect('sports:home')


def reg(request):

    if request.method == 'POST':
        c = request.POST['fullname']
        d = request.POST['youremail']
        e = request.POST['password']
        f = request.POST['confirm-password']
        g = request.POST['firstname']
        h = request.POST['lastname']
        print(c,d,g,h)
        if (e == f):

            if (User.objects.filter(username=c).exists()):
                messages.error(request, "username already exist")
                return redirect('sports:register-page')
            elif (User.objects.filter(email=d).exists()):
                messages.error(request, "email already exist")
                return redirect('sports:register-page')
            else:
                z = User.objects.create_user(username=c, email=d, password=e, first_name=g, last_name=h)
                z.save()
                return render(request, 'register.html')

        else:
            messages.error(request, "password doesn't match")
            return redirect('sports:register-page')
    return render(request, 'register.html')

def blog (request):
    ad = readmore.objects.order_by('-date')[0:1]
    bd = readmore.objects.order_by('date')[1:]
    return render(request, 'Blog.html', {'ad': ad, 'bd': bd})

def about (request):
    return render(request, 'about.html')

def team (request):
    return render(request, 'team.html')

def news (request):
    return render(request, 'news.html')

def contact (request):
    subject='melcow to the world of sports'
    message='Sport includes all forms of competitive physical activity or games which,[1] through casual or organised participation, at least in part aim to use, maintain or improve physical ability and skills while providing enjoyment to participants, and in some cases, entertainment for spectators.[2] Hundreds of sports exist, from those between single contestants, through to those with hundreds of simultaneous participants, either in teams or competing as individuals. In certain sports such as racing, many contestants may compete, simultaneously or consecutively, with one winner; in others, the contest (a match) is between two sides, each attempting to exceed the other. Some sports allow a "tie" or "draw", in which there is no single winner; others provide tie-breaking methods to ensure one winner and one loser. A number of contests may be arranged in a tournament producing a champion. Many sports leagues make an annual champion by arranging games in a regular sports season, followed in some cases by playoffs.'
    recipent=request.GET.get('email_id')
    send_mail(subject,message,EMAIL_HOST_USER,[recipent], fail_silently=False)
    return render(request, 'contact.html',{'f':recipent})

def search (request):
    a=request.GET.get('f', None)
    results=sports.objects.filter(Q(head__icontains=a) | Q(sub__icontains=a))
    result=match.objects.filter(Q(team1__icontains=a) | Q(team2__icontains=a))
    return render(request, 'searchresult.html', {'search1':results,'search': result})

def read (request):
     return render(request,'single-blog.html')

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% include 'head.html' %}
</head>
<body>
    {% include 'header.html' %}
    {% block content %}
    {% endblock content %}
    {% include 'footer.html' %}
    {% include 'script.html' %}
</body>
</html>

templates/contact.html
{% extends 'base.html' %}
{%load static%}
{% block content %}

   <body class="game_info" data-spy="scroll" data-target=".header">
      <!-- LOADER -->
      <div id="preloader">
         <img class="preloader" src="images/loading-img.gif" alt="">
      </div>
      <!-- END LOADER -->
      <section id="top">
         <header>
            <div class="container">
               <div class="header-top">
                  <div class="row">
                     <div class="col-md-6">
                        <div class="full">
                           <div class="logo">
                              <a href="index.html"><img src="images/logo.png" alt="#" /></a>
                           </div>
                        </div>
                     </div>
                     <div class="col-md-6">
                        <div class="right_top_section">
                           <!-- social icon -->
                           <ul class="social-icons pull-left">
                              <li><a class="facebook" href="#"><i class="fa fa-facebook"></i></a></li>
                              <li><a class="twitter" href="#"><i class="fa fa-twitter"></i></a></li>
                              <li><a class="youtube" href="#"><i class="fa fa-youtube-play"></i></a></li>
                              <li><a class="pinterest" href="#"><i class="fa fa-pinterest-p"></i></a></li>
                           </ul>
                           <!-- end social icon -->
                           <!-- button section -->
                           <ul class="login">
                              <li class="login-modal">
                                 <a href="#" class="login"><i class="fa fa-user"></i>Login</a>
                              </li>
                              <li>
                                 <div class="cart-option">
                                    <a href="#"><i class="fa fa-shopping-cart"></i>Register</a>
                                 </div>
                              </li>
                           </ul>
                           <!-- end button section -->
                        </div>
                     </div>
                  </div>
               </div>
               <div class="header-bottom">
                  <div class="row">
                     <div class="col-md-12">
                        <div class="full">
                           <div class="main-menu-section">
                              <div class="menu">
                                 <nav class="navbar navbar-inverse">
                                    <div class="navbar-header">
                                       <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".js-navbar-collapse">
                                       <span class="sr-only">Toggle navigation</span>
                                       <span class="icon-bar"></span>
                                       <span class="icon-bar"></span>
                                       <span class="icon-bar"></span>
                                       </button>
                                       <a class="navbar-brand" href="#">Menu</a>
                                    </div>
                                    <div class="collapse navbar-collapse js-navbar-collapse">
                                       <ul class="nav navbar-nav">
                                          <li class="active"><a href="{% url 'sports:home' %}">Home</a></li>
                                          <li><a href="{% url 'sports:about-page' %}">About</a></li>
                                          <li><a href="{% url 'sports:team-page' %}">Team</a></li>
                                          <li><a href="{% url 'sports:news-page' %}">News</a></li>
                                          <li class="dropdown mega-dropdown">
                                             <a href="match" class="dropdown-toggle" data-toggle="dropdown">Match<span class="caret"></span></a>				
                                             <ul class="dropdown-menu mega-dropdown-menu">
                                                <li class="col-sm-8">
                                                   <ul>
                                                      <li class="dropdown-header">Men Collection</li>
                                                      <div id="menCollection" class="carousel slide" data-ride="carousel">
                                                         <div class="carousel-inner">
                                                            <div class="item active">
                                                               <div class="banner-for-match"><a href="#"><img class="img-responsive" src="images/match-banner1.jpg" alt="#" /></a></div>
                                                            </div>
                                                            <!-- End Item -->
                                                            <div class="item">
                                                               <div class="banner-for-match"><a href="#"><img class="img-responsive" src="images/match-banner1.jpg" alt="#" /></a></div>
                                                            </div>
                                                            <!-- End Item -->
                                                            <div class="item">
                                                               <div class="banner-for-match"><a href="#"><img class="img-responsive" src="images/match-banner1.jpg" alt="#" /></a></div>
                                                            </div>
                                                            <!-- End Item -->                                
                                                         </div>
                                                         <!-- End Carousel Inner -->
                                                         <!-- Controls -->
                                                         <a class="left carousel-control" href="#menCollection" role="button" data-slide="prev">
                                                         <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                                                         <span class="sr-only">Previous</span>
                                                         </a>
                                                         <a class="right carousel-control" href="#menCollection" role="button" data-slide="next">
                                                         <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                                                         <span class="sr-only">Next</span>
                                                         </a>
                                                      </div>
                                                      <!-- /.carousel -->
                                                   </ul>
                                                </li>
                                                <li class="col-sm-4">
                                                   <ul class="menu-inner">
                                                      <li class="dropdown-header">Next Matchs</li>
                                                      <li><a href="#">Contrary vs classical</a></li>
                                                      <li><a href="#">Discovered vs undoubtable</a></li>
                                                      <li><a href="#">Contrary vs classical</a></li>
                                                      <li><a href="#">Discovered vs undoubtable</a></li>
                                                      <li><a href="#">Contrary vs classical</a></li>
                                                      <li><a href="#">Discovered vs undoubtable</a></li>
                                                      <li><a href="#">Contrary vs classical</a></li>
                                                      <li><a href="#">Discovered vs undoubtable</a></li>
                                                   </ul>
                                                </li>
                                             </ul>
                                          </li>
                                          <li><a href="{% url 'sports:blog-page' %}">Blog</a></li>
                                          <li><a href="contact.html">contact</a></li>
                                       </ul>
                                    </div>
                                    <!-- /.nav-collapse -->
                                 </nav>
                                 <div class="search-bar">
                                    <div id="imaginary_container">
                                       <div class="input-group stylish-input-group">
                                          <input type="text" class="form-control"  placeholder="Search" >
                                          <span class="input-group-addon">
                                          <button type="submit"><i class="fa fa-search" aria-hidden="true"></i></button>  
                                          </span>
                                       </div>
                                    </div>
                                 </div>
                              </div>
                           </div>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </header>
         <div class="inner-page-banner">
            <div class="container">
            </div>
         </div>
         <div class="inner-information-text">
            <div class="container">
               <h3>Contact</h3>
               <ul class="breadcrumb">
                  <li><a href="index.html">Home</a></li>
                  <li class="active">Contact</li>
               </ul>
            </div>
         </div>
         </section>
         <div>
            {% if f is None %}
               <form action="{% url 'sports:contact-page' %}" >
                  <input type="text" placeholder="email" name="email_id" size="100">
                  <input type="submit" value="subscribe">
               </form>
            {% else %}
               <h>{{ f }}</h>
               <form action=".">
                  <input type="submit" value="resend email" name=" ">
               </form>
            {% endif %}
         </div>

      <section id="contant" class="contant main-heading team">
         <div class="row">
            <div class="container">
               <div class="contact">
                  <div class="col-md-12">
                     <div class="map"> 
                        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3503.580671926123!2d77.31096031514461!3d28.582351982437654!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x390cfcad59dc9d0b%3A0xe4060212422c0b9a!2sLeopedia+Web+Solutions!5e0!3m2!1sen!2sin!4v1511962485065" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
                     </div>
                  </div>
                  <div class="col-md-6">
                     <div class="contact-info">
                        <div class="kode-section-title">
                           <h3>Contact Info</h3>
                        </div>
                        <div class="kode-forminfo">
                           <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam aliquip..</p>
                           <ul class="kode-form-list">
                              <li>
                                 <i class="fa fa-home"></i> 
                                 <p><strong>Address:</strong> 805 consectetur adipiscing elit, sed do eiusmod tempor</p>
                              </li>
                              <li>
                                 <i class="fa fa-phone"></i> 
                                 <p><strong>Phone:</strong>  123 456 7890</p>
                              </li>
                              <li>
                                 <i class="fa fa-envelope-o"></i> 
                                 <p><strong>Email:</strong> Info@sportyleague.com</p>
                              </li>
                           </ul>
                        </div>
                     </div>
                  </div>
                  <div class="col-md-6">
                     <div class="contact-us">
                        <form method="post" class="comments-form" id="contactform">
                           <ul>
                              <li><input type="text" id="name" name="name" class="required" placeholder="Name *"></li>
                              <li><input type="text" id="email" name="email" class="required email" placeholder="Email *"></li>
                              <li><input type="text" name="address" id="address" placeholder="Address:"></li>
                              <li><textarea name="message" id="message" placeholder="Add your message"></textarea></li>
                              <li><input class="thbg-color" type="submit" value="send"></li>
                           </ul>
                           <div class="hidden-me" id="contact_form_responce">
                              <p></p>
                           </div>
                        </form>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </section>

      <a href="#home" data-scroll class="dmtop global-radius"><i class="fa fa-angle-up"></i></a>
      <!-- ALL JS FILES -->

   </body>
</html>
{% endblock content %}

templates/header.html
{%load static%}
{%static 'images' as baseUrl%}
<header>
            <div class="container">
               <div class="header-top">
                  <div class="row">
                     <div class="col-md-6">
                        <div class="full">
                           <div class="logo">
                              <a href="index.html"><img src="{%static 'images/logo.png'%}" alt="#" /></a>
                           </div>
                        </div>
                     </div>
                     <div class="col-md-6">
                        <div class="right_top_section">
                           <!-- social icon -->
                           <ul class="social-icons pull-left">
                              <li><a class="facebook" href="https://www.facebook.com/BlueHorse.Jaya"><i class="fa fa-facebook"></i></a></li>
                              <li><a class="twitter" href="#"><i class="fa fa-twitter"></i></a></li>
                              <li><a class="youtube" href="https://www.youtube.com/channel/UC7w3h8WuNFbLto06i5qU9xQ"><i class="fa fa-youtube-play"></i></a></li>
                              <li><a class="pinterest" href="#"><i class="fa fa-pinterest-p"></i></a></li>
                           </ul>
                           <!-- end social icon -->
                           <!-- button section -->
                           <ul class="login">
                              {% if user.is_authenticated %}
                                 <li class="logout-modal">
                                    <a href="{% url 'sports:logout-page'%}" class="logout"><i class="fa fa-user"></i>Logout</a>
                                 </li>
                              {% else %}
                                 <li class="login-modal">
                                    <a href="{% url 'sports:login-page'%}" class="login"><i class="fa fa-user"></i>Login</a>
                                 </li>
                                 <li>
                                    <div class="cart-option">
                                       <a href="{% url 'sports:register-page' %}"><i class="fa fa-shopping-cart"></i>Register</a>
                                    </div>
                                 </li>
                              {% endif %}
                           </ul>
                           <!-- end button section -->
                        </div>
                     </div>
                  </div>
               </div>
               <div class="header-bottom">
                  <div class="row">
                     <div class="col-md-12">
                        <div class="full">
                           <div class="main-menu-section">
                              <div class="menu">
                                 <nav class="navbar navbar-inverse">
                                    <div class="navbar-header">
                                       <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".js-navbar-collapse">
                                       <span class="sr-only">Toggle navigation</span>
                                       <span class="icon-bar"></span>
                                       <span class="icon-bar"></span>
                                       <span class="icon-bar"></span>
                                       </button>
                                       <a class="navbar-brand" href="#">Menu</a>
                                    </div>
                                    <div class="collapse navbar-collapse js-navbar-collapse">
                                       <ul class="nav navbar-nav">
                                          <li class="active"><a href="{% url 'sports:home' %}">Home</a></li>
                                          <li><a href="{% url 'sports:about-page' %}">About</a></li>
                                          <li><a href="{% url 'sports:team-page' %}">Team</a></li>
                                          <li><a href="{% url 'sports:news-page' %}">News</a></li>
                                          <li class="dropdown mega-dropdown">
                                             <a href="match" class="dropdown-toggle" data-toggle="dropdown">Match<span class="caret"></span></a>
                                             <ul class="dropdown-menu mega-dropdown-menu">
                                                <li class="col-sm-8">
                                                   <ul>
                                                      <li class="dropdown-header">Men Collection</li>
                                                      <div id="menCollection" class="carousel slide" data-ride="carousel">
                                                         <div class="carousel-inner">
                                                            <div class="item active">
                                                               <div class="banner-for-match"><a href="#"><img class="img-responsive" src="{%static 'images/match-banner1.jpg'%}" alt="#" /></a></div>
                                                            </div>
                                                            <!-- End Item -->
                                                            <div class="item">
                                                               <div class="banner-for-match"><a href="#"><img class="img-responsive" src="{%static 'images/match-banner1.jpg'%}" alt="#" /></a></div>
                                                            </div>
                                                            <!-- End Item -->
                                                            <div class="item">
                                                               <div class="banner-for-match"><a href="#"><img class="img-responsive" src="{%static 'images/match-banner1.jpg'%}" alt="#" /></a></div>
                                                            </div>
                                                            <!-- End Item -->
                                                         </div>
                                                         <!-- End Carousel Inner -->
                                                         <!-- Controls -->
                                                         <a class="left carousel-control" href="#menCollection" role="button" data-slide="prev">
                                                         <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                                                         <span class="sr-only">Previous</span>
                                                         </a>
                                                         <a class="right carousel-control" href="#menCollection" role="button" data-slide="next">
                                                         <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                                                         <span class="sr-only">Next</span>
                                                         </a>
                                                      </div>
                                                      <!-- /.carousel -->
                                                   </ul>
                                                </li>
                                                <li class="col-sm-4">
                                                   <ul class="menu-inner">
                                                      <li class="dropdown-header">Next Matchs</li>
                                                      <li><a href="#">Contrary vs classical</a></li>
                                                      <li><a href="#">Discovered vs undoubtable</a></li>
                                                      <li><a href="#">Contrary vs classical</a></li>
                                                      <li><a href="#">Discovered vs undoubtable</a></li>
                                                      <li><a href="#">Contrary vs classical</a></li>
                                                      <li><a href="#">Discovered vs undoubtable</a></li>
                                                      <li><a href="#">Contrary vs classical</a></li>
                                                      <li><a href="#">Discovered vs undoubtable</a></li>
                                                   </ul>
                                                </li>
                                             </ul>
                                          </li>
                                          <li><a href="{% url 'sports:blog-page' %}">Blog</a></li>
                                          <li><a href="{% url 'sports:contact-page' %}">contact</a></li>
                                       </ul>
                                    </div>
                                    <!-- /.nav-collapse -->
                                 </nav>
                                 <div class="search-bar">
                                    <form action="{% url 'sports:searchresult-page' %}">
                                        <div id="imaginary_container">
                                           <div class="input-group stylish-input-group">
                                              <input type="text" class="form-control"name="f" placeholder="search" >
                                              <span class="input-group-addon">
                                              <button type="submit"><i class="fa fa-search" aria-hidden="true"></i></button>
                                              </span>
                                           </div>
                                        </div>
                                   </form>
                                 </div>
                              </div>
                           </div>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
</header>